anchor_version = "0.28.0"

[registry]
url = "https://anchor.projectserum.com"

[programs.localnet]
onda_compression = "onda1FgCsQMC4zBhsjGjKoHDgGp6q7pK48HQaVXf28d"
onda_moderation = "5o1PS9vW57YUezjCuN7aycLnACKkaxGyb7Ak7pdcK6sw"
onda_awards = "AwrdSLTcfNkVSARz8YoNYcVhknD7oxm7t3EqyYZ9bPK5"
onda_profile = "ondapcq2qXTSynRieMCE9BjRsZ2XALEEZZunkwbhCPF"
onda_namespace = "ona67gSygPUkb34U5sgPZK7AkgXDJJrNoi5nrraEHvE"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"

[[test.validator.clone]]
address = "6MhUAJtKdJx3RDCffUsJsQm8xy9YhhywjEmMYrxRc5j6"