anchor_version = "0.26.0"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false

[programs.localnet]
onda_listings = "CKUdSYh8hQp8WYXDbWDFks5AUKopeS5D336PMqePh5bs"
onda_social = "BWWPkJpv6fV2ZM5aNua8btxBXooWdW2qjWwUDBhz1p9S"

[programs.devnet]
onda_listings = "CKUdSYh8hQp8WYXDbWDFks5AUKopeS5D336PMqePh5bs"
onda_social = "BWWPkJpv6fV2ZM5aNua8btxBXooWdW2qjWwUDBhz1p9S"

[programs.mainnet]
onda_listings = "CKUdSYh8hQp8WYXDbWDFks5AUKopeS5D336PMqePh5bs"
onda_social = "BWWPkJpv6fV2ZM5aNua8btxBXooWdW2qjWwUDBhz1p9S"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"