anchor_version = "0.24.2"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false

[programs.localnet]
onda_listings = "F2BTn5cmYkTzo52teXhG6jyLS3y2BujdE56yZaGyvxwC"

[programs.devnet]
onda_listings = "F2BTn5cmYkTzo52teXhG6jyLS3y2BujdE56yZaGyvxwC"

[programs.mainnet]
onda_listings = "F2BTn5cmYkTzo52teXhG6jyLS3y2BujdE56yZaGyvxwC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"