anchor_version = "0.26.0"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false

[programs.localnet]
onda_compression = "ondaUaJpDBZZQzpGe5Tr391CbuJH1UpZuRcS7sZU2GB"
onda_moderation = "5o1PS9vW57YUezjCuN7aycLnACKkaxGyb7Ak7pdcK6sw"
onda_bloom = "onda3Sxku2NT88Ho8WfEgbkavNEELWzaguvh4itdn3C"
onda_profile = "ondapcq2qXTSynRieMCE9BjRsZ2XALEEZZunkwbhCPF"
onda_namespace = "GCZ4prh8BBkoTePCNF7VfWuNPhRVgwDKfxy8Uv4ERC8V"

[programs.devnet]
onda_compression = "ondaUaJpDBZZQzpGe5Tr391CbuJH1UpZuRcS7sZU2GB"
onda_moderation = "5o1PS9vW57YUezjCuN7aycLnACKkaxGyb7Ak7pdcK6sw"
onda_bloom = "onda3Sxku2NT88Ho8WfEgbkavNEELWzaguvh4itdn3C"
onda_profile = "ondapcq2qXTSynRieMCE9BjRsZ2XALEEZZunkwbhCPF"
onda_namespace = "GCZ4prh8BBkoTePCNF7VfWuNPhRVgwDKfxy8Uv4ERC8V"


[programs.mainnet]
onda_compression = "ondaUaJpDBZZQzpGe5Tr391CbuJH1UpZuRcS7sZU2GB"
onda_moderation = "5o1PS9vW57YUezjCuN7aycLnACKkaxGyb7Ak7pdcK6sw"
onda_bloom = "onda3Sxku2NT88Ho8WfEgbkavNEELWzaguvh4itdn3C"
onda_profile = "ondapcq2qXTSynRieMCE9BjRsZ2XALEEZZunkwbhCPF"
onda_namespace = "GCZ4prh8BBkoTePCNF7VfWuNPhRVgwDKfxy8Uv4ERC8V"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"

[[test.validator.clone]]
address = "6MhUAJtKdJx3RDCffUsJsQm8xy9YhhywjEmMYrxRc5j6"